// Generated by CoffeeScript 1.6.3
(function() {
  var RowStream, through;

  through = require('through');

  module.exports = RowStream = function(columns) {
    return through(function(data) {
      var cells;
      cells = columns.map(function(column) {
        var cell;
        cell = {};
        cell.value = data[column.property];
        if (column.className) {
          cell.className = column.className;
        } else {
          cell.className = column.property;
        }
        cell.serialized = JSON.stringify(cell.value);
        if (column.template) {
          cell.text = column.template(cell.value, data);
        } else {
          cell.text = cell.value;
        }
        return cell;
      });
      return this.emit('data', {
        cells: cells,
        obj: data
      });
    });
  };

}).call(this);
